// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCafe.Web.Data;

#nullable disable

namespace MyCafe.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319102356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCafe.Web.Models.ChiTietHoaDonBan", b =>
                {
                    b.Property<string>("MaHDB")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaSP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("KhuyenMai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaHDB", "MaSP");

                    b.ToTable("tb_CTHDB");
                });

            modelBuilder.Entity("MyCafe.Web.Models.ChiTietHoaDonNhap", b =>
                {
                    b.Property<string>("MaHDN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("KhuyenMai")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaHDN", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("tb_CTHDN");
                });

            modelBuilder.Entity("MyCafe.Web.Models.CongDung", b =>
                {
                    b.Property<string>("MaCongDung")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenCongDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCongDung");

                    b.ToTable("tb_Congdung");
                });

            modelBuilder.Entity("MyCafe.Web.Models.HoaDonBan", b =>
                {
                    b.Property<string>("MaHDB")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayBan")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaHDB");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("tb_HDB");
                });

            modelBuilder.Entity("MyCafe.Web.Models.HoaDonNhap", b =>
                {
                    b.Property<string>("MaHDN")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaHDN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("tb_HDN");
                });

            modelBuilder.Entity("MyCafe.Web.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKH");

                    b.ToTable("tb_Khachhang");
                });

            modelBuilder.Entity("MyCafe.Web.Models.Loai", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("tb_Loai");
                });

            modelBuilder.Entity("MyCafe.Web.Models.NCC", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNCC");

                    b.ToTable("tb_NCC");
                });

            modelBuilder.Entity("MyCafe.Web.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaQue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaQue");

                    b.ToTable("tb_Nhanvien");
                });

            modelBuilder.Entity("MyCafe.Web.Models.Que", b =>
                {
                    b.Property<string>("MaQue")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenQue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQue");

                    b.ToTable("tb_Que");
                });

            modelBuilder.Entity("MyCafe.Web.Models.Sanpham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MaCongDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSP");

                    b.HasIndex("MaCongDung");

                    b.HasIndex("MaLoai");

                    b.ToTable("tb_Sanpham");
                });

            modelBuilder.Entity("MyCafe.Web.Models.ChiTietHoaDonBan", b =>
                {
                    b.HasOne("MyCafe.Web.Models.HoaDonBan", "HoaDonBan")
                        .WithMany("ChiTietHoaDonBans")
                        .HasForeignKey("MaHDB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDonBan");
                });

            modelBuilder.Entity("MyCafe.Web.Models.ChiTietHoaDonNhap", b =>
                {
                    b.HasOne("MyCafe.Web.Models.HoaDonNhap", "HoaDonNhap")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("MaHDN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyCafe.Web.Models.Sanpham", "Sanpham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDonNhap");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("MyCafe.Web.Models.HoaDonBan", b =>
                {
                    b.HasOne("MyCafe.Web.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyCafe.Web.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDonBans")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("MyCafe.Web.Models.HoaDonNhap", b =>
                {
                    b.HasOne("MyCafe.Web.Models.NCC", "NCC")
                        .WithMany("HoaDonNhaps")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyCafe.Web.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDonNhaps")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NCC");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("MyCafe.Web.Models.NhanVien", b =>
                {
                    b.HasOne("MyCafe.Web.Models.Que", "Que")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaQue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Que");
                });

            modelBuilder.Entity("MyCafe.Web.Models.Sanpham", b =>
                {
                    b.HasOne("MyCafe.Web.Models.CongDung", "CongDung")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaCongDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyCafe.Web.Models.Loai", "Loai")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CongDung");

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("MyCafe.Web.Models.CongDung", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("MyCafe.Web.Models.HoaDonBan", b =>
                {
                    b.Navigation("ChiTietHoaDonBans");
                });

            modelBuilder.Entity("MyCafe.Web.Models.HoaDonNhap", b =>
                {
                    b.Navigation("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("MyCafe.Web.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDonBans");
                });

            modelBuilder.Entity("MyCafe.Web.Models.Loai", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("MyCafe.Web.Models.NCC", b =>
                {
                    b.Navigation("HoaDonNhaps");
                });

            modelBuilder.Entity("MyCafe.Web.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDonBans");

                    b.Navigation("HoaDonNhaps");
                });

            modelBuilder.Entity("MyCafe.Web.Models.Que", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
